### ISSUE TITLE
The problem about running start

### ISSUE THREAD

**Issue by MPHarryZhang** [Smart-Trafficlab/TransformerLight#1]
Thank your research very much. We really like this work, and we are working on similar research. When we ran these files "run_decision_transforlight.py", "run_DT.py", and "run_TT.py", they popped **this error "FileNotFoundError: [Errno 2] No such file or directory: './memory/data_jn_1.pkl'"**.
We know the file ".pkl" is the trajectory of TSC used for offline RL. But we don't know how to build it. In other words, we don't know the format of the contents of the file ".pkl". Could you tell us how to fix the error and run the program successfully? Or can you provide relevant files ".pkl"? Thank you very much.

**Comment by Smart-Trafficlab** [comment]
We are very grateful for your attention and support to our work. Meanwhile, we are deeply sorry for the previous oversight. Now that we have updated the file contents, given the large size of the dataset, you can access and download the dataset at the following address: https://drive.google.com/drive/folders/1Y_gDn4l6bWl6M97WAtWnsIfuwVhDNVD6?usp=drive_link

**Comment by MPHarryZhang** [comment]
> We are very grateful for your attention and support to our work. Meanwhile, we are deeply sorry for the previous oversight. Now that we have updated the file contents, given the large size of the dataset, you can access and download the dataset at the following address: https://drive.google.com/drive/folders/1Y_gDn4l6bWl6M97WAtWnsIfuwVhDNVD6?usp=drive_link

Thanks very much for your reply. I look forward to continuing to communicate with you in the future.
